#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

admin_email=$(ynh_user_get_info $admin 'mail')
secret_key=$(ynh_string_random --length=32 | base64)

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression "Storing installation settings..."

ynh_app_setting_set --key=admin_email --value=$admin_email
ynh_app_setting_set --key=secret_key --value=$secret_key

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir/$app"

# Create the media directory, where uploads will be stored
mkdir -p $install_dir/media

# Create the cargo directory
mkdir -p $install_dir/.cargo/bin

# Move binaries
mv $install_dir/$app/bin/* $install_dir/.cargo/bin/
chmod +x $install_dir/.cargo/bin/*

# Remove empty bin directory
ynh_safe_rm "$install_dir/$app/bin"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 750 "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:$app "$install_dir"
#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# SPECIFIC SETUP
#=================================================
# CREATE LOG FOLDER
#=================================================

mkdir -p "/var/log/$app"
#REMOVEME? Assuming ynh_config_add_logrotate is called, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R "$app":"$app" "/var/log/$app"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding a config file..."

ynh_config_add --template=".env" --destination="$install_dir/$app/.env"

#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 400 "$install_dir/$app/.env"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown $app:$app "$install_dir/$app/.env"

#=================================================
# MAKE SETUP
#=================================================
ynh_script_progression "Making setup..."

# Set right permissions

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R "$app":"$app" $install_dir
export PATH="$PATH:$install_dir/.cargo/bin:$install_dir/.local/bin:/usr/local/sbin"

pushd $install_dir/$app
	ynh_exec_as_app PATH=$PATH plm migration run

	# Add new instance
	if [ $registration -eq 1 ]
	then
		ynh_exec_as_app PATH=$PATH plm instance new  --domain "$domain" --name "$name" -l 'CC-BY'
	else
		ynh_exec_as_app PATH=$PATH plm instance new --private --domain "$domain" --name "$name" -l 'CC-BY'
	fi

	# Add admin user
	ynh_exec_as_app PATH=$PATH plm users new --admin -n "$admin" -N "$admin"  --email "$admin_email" --password "$password"

	# Initialise search index
	ynh_exec_as_app PATH=$PATH plm search init -p $install_dir/$app
popd

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring $app's systemd service..."

# Create a dedicated systemd config
ynh_config_add_systemd

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

yunohost service add $app --description="$app daemon for Plume" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd" --wait_until="Started plume"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
