#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app >/dev/null
then
	ynh_script_progression "Removing $app service integration..."
	yunohost service remove $app
fi

# Remove the dedicated systemd config
ynh_config_remove_systemd

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

# Remove the dedicated NGINX config
ynh_config_remove_nginx

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression "Removing dependencies..."

export PATH="$PATH:$install_dir/.cargo/bin:$install_dir/.local/bin:/usr/local/sbin"

pushd $install_dir/$app
	ynh_exec_as_app PATH=$PATH cargo uninstall diesel_cli
popd

if [ -d "/usr/local/lib/rustlib" ]; then
	sudo /usr/local/lib/rustlib/uninstall.sh
fi

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression "Removing various files..."

# Remove the log files

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
